<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="script.xinche.CheXingShouCangTest" tests="10" failures="1" timestamp="8 Sep 2017 07:21:52 GMT" time="1353.351" errors="1">
  <testcase name="xinche_chexingshoucang_testcase1" time="142.063" classname="script.xinche.CheXingShouCangTest">
    <failure type="java.lang.AssertionError" message="检查车型收藏为空 expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: 检查车型收藏为空 expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertFalse(Assert.java:63)
	at script.xinche.CheXingShouCangTest.xinche_chexingshoucang_testcase1(CheXingShouCangTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- xinche_chexingshoucang_testcase1 -->
  <testcase name="xinche_chexingshoucang_testcase5" time="106.901" classname="script.xinche.CheXingShouCangTest"/>
  <testcase name="xinche_chexingshoucang_testcase8" time="243.850" classname="script.xinche.CheXingShouCangTest"/>
  <testcase name="xinche_chexingshoucang_testcase3" time="125.447" classname="script.xinche.CheXingShouCangTest"/>
  <testcase name="xinche_chexingshoucang_testcase9" time="108.093" classname="script.xinche.CheXingShouCangTest"/>
  <testcase name="xinche_chexingshoucang_testcase7" time="110.725" classname="script.xinche.CheXingShouCangTest"/>
  <testcase name="xinche_chexingshoucang_testcase2" time="186.513" classname="script.xinche.CheXingShouCangTest"/>
  <testcase name="xinche_chexingshoucang_testcase10" time="194.459" classname="script.xinche.CheXingShouCangTest"/>
  <testcase name="xinche_chexingshoucang_testcase6" time="17.455" classname="script.xinche.CheXingShouCangTest">
    <error type="java.lang.NoClassDefFoundError" message="models/ErShouChe">
      <![CDATA[java.lang.NoClassDefFoundError: models/ErShouChe
	at script.xinche.CheXingShouCangTest.xinche_chexingshoucang_testcase6(CheXingShouCangTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
Caused by: java.lang.ClassNotFoundException: models.ErShouChe
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 25 more
]]>
    </error>
  </testcase> <!-- xinche_chexingshoucang_testcase6 -->
  <testcase name="xinche_chexingshoucang_testcase4" time="117.845" classname="script.xinche.CheXingShouCangTest"/>
</testsuite> <!-- script.xinche.CheXingShouCangTest -->
